com.dwarfeng.acckeeper.jdbc.driver=com.mysql.cj.jdbc.Driver
com.dwarfeng.acckeeper.jdbc.url=\
  jdbc:mysql://your-host-here:3306/acckeeper?serverTimezone=Asia/Shanghai&autoReconnect=true
com.dwarfeng.acckeeper.jdbc.username=root
com.dwarfeng.acckeeper.jdbc.password=your-password-here
com.dwarfeng.acckeeper.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
